"$schema" = "../../node_modules/wrangler/config-schema.json"

name = "mosoo-web"
compatibility_date = "2026-06-01"

[assets]
directory = "./dist"
not_found_handling = "single-page-application"

[env.prod]
name = "mosoo-web-prod"
workers_dev = false

[[env.prod.routes]]
pattern = "mosoo.ai"
custom_domain = true
