// Generated by pkgs/runtime-catalog/scripts/generate-runtime-catalog.ts.
// Source: pkgs/runtime-catalog/catalog/runtime-catalog.jsonc
// Do not edit this file by hand.

export const GENERATED_MODEL_DEFAULT_IDS = {
  anthropic: "claude-sonnet-4-5",
  deepseek: "deepseek-v4-pro",
  openai: "gpt-5.4",
} as const;

export const GENERATED_VENDOR_CATALOG = [
  {
    apiBaseEnvVar: "ANTHROPIC_BASE_URL",
    apiKeyEnvVar: "ANTHROPIC_API_KEY",
    authHeader: {
      apiKeyHeader: "x-api-key",
      extraHeaders: {
        "anthropic-version": "2023-06-01",
      },
      scheme: "api-key",
    },
    defaultApiBase: "https://api.anthropic.com",
    label: "Anthropic",
    vendorId: "anthropic",
  },
  {
    apiBaseEnvVar: "OPENAI_BASE_URL",
    apiKeyEnvVar: "OPENAI_API_KEY",
    authHeader: {
      apiKeyHeader: "Authorization",
      scheme: "bearer",
    },
    defaultApiBase: "https://api.openai.com/v1",
    label: "OpenAI",
    vendorId: "openai",
  },
  {
    apiBaseEnvVar: "OPENAI_COMPATIBLE_BASE_URL",
    apiKeyEnvVar: "OPENAI_COMPATIBLE_API_KEY",
    authHeader: {
      apiKeyHeader: "Authorization",
      scheme: "bearer",
    },
    label: "OpenAI-Compatible",
    vendorId: "openai-compatible",
  },
  {
    apiBaseEnvVar: "DEEPSEEK_BASE_URL",
    apiKeyEnvVar: "DEEPSEEK_API_KEY",
    authHeader: {
      apiKeyHeader: "Authorization",
      scheme: "bearer",
    },
    defaultApiBase: "https://api.deepseek.com",
    label: "DeepSeek",
    openCodeProvider: {
      apiBaseOption: "baseURL",
      kind: "openai-compatible",
      npmPackage: "@ai-sdk/openai-compatible",
    },
    vendorId: "deepseek",
  },
  {
    apiKeyEnvVar: "OPENCODE_API_KEY",
    authHeader: {
      apiKeyHeader: "Authorization",
      scheme: "bearer",
    },
    defaultApiBase: "https://opencode.ai/zen/v1",
    label: "OpenCode Zen",
    vendorId: "opencode",
  },
] as const;

export const GENERATED_PRESET_MODEL_CATALOG = [
  {
    displayName: "Claude Opus 4.7",
    modelId: "claude-opus-4-7",
    protocol: "anthropic-messages",
    vendorId: "anthropic",
    vendorLabel: "Anthropic",
  },
  {
    displayName: "Claude Opus 4.6",
    modelId: "claude-opus-4-6",
    protocol: "anthropic-messages",
    vendorId: "anthropic",
    vendorLabel: "Anthropic",
  },
  {
    displayName: "Claude Opus 4.5",
    modelId: "claude-opus-4-5",
    protocol: "anthropic-messages",
    vendorId: "anthropic",
    vendorLabel: "Anthropic",
  },
  {
    displayName: "Claude Sonnet 4.6",
    modelId: "claude-sonnet-4-6",
    protocol: "anthropic-messages",
    vendorId: "anthropic",
    vendorLabel: "Anthropic",
  },
  {
    displayName: "Claude Sonnet 4.5",
    modelId: "claude-sonnet-4-5",
    protocol: "anthropic-messages",
    vendorId: "anthropic",
    vendorLabel: "Anthropic",
  },
  {
    displayName: "Claude Haiku 4.5",
    modelId: "claude-haiku-4-5",
    protocol: "anthropic-messages",
    vendorId: "anthropic",
    vendorLabel: "Anthropic",
  },
  {
    displayName: "GPT-5.5",
    modelId: "gpt-5.5",
    protocol: "openai-responses",
    vendorId: "openai",
    vendorLabel: "OpenAI",
  },
  {
    displayName: "GPT-5.4",
    modelId: "gpt-5.4",
    protocol: "openai-responses",
    vendorId: "openai",
    vendorLabel: "OpenAI",
  },
  {
    displayName: "GPT-5.4 mini",
    modelId: "gpt-5.4-mini",
    protocol: "openai-responses",
    vendorId: "openai",
    vendorLabel: "OpenAI",
  },
  {
    displayName: "GPT-5.3",
    modelId: "gpt-5.3",
    protocol: "openai-responses",
    vendorId: "openai",
    vendorLabel: "OpenAI",
  },
  {
    displayName: "GPT-5.2",
    modelId: "gpt-5.2",
    protocol: "openai-responses",
    vendorId: "openai",
    vendorLabel: "OpenAI",
  },
  {
    displayName: "DeepSeek V4 Pro",
    modelId: "deepseek-v4-pro",
    protocol: "openai-chat-completions",
    vendorId: "deepseek",
    vendorLabel: "DeepSeek",
  },
  {
    displayName: "Qwen3.6 Plus",
    modelId: "qwen3.6-plus",
    protocol: "anthropic-messages",
    vendorId: "opencode",
    vendorLabel: "OpenCode Zen",
  },
  {
    displayName: "GLM 5.2",
    modelId: "glm-5.2",
    protocol: "openai-chat-completions",
    vendorId: "opencode",
    vendorLabel: "OpenCode Zen",
  },
  {
    displayName: "MiniMax M2.7",
    modelId: "minimax-m2.7",
    protocol: "openai-chat-completions",
    vendorId: "opencode",
    vendorLabel: "OpenCode Zen",
  },
  {
    displayName: "Gemini 3.5 Flash",
    modelId: "gemini-3.5-flash",
    protocol: "google-gemini",
    vendorId: "opencode",
    vendorLabel: "OpenCode Zen",
  },
] as const;

export const GENERATED_RUNTIME_CATALOG = [
  {
    acceptsCustomProvider: false,
    defaultIdentity: {
      modelId: "claude-sonnet-4-5",
      providerId: "anthropic",
    },
    display: {
      color: "#D97757",
      iconKey: "claude-code",
      providerLabel: "Anthropic",
    },
    label: "Claude Agent SDK",
    runtimeId: "claude-agent-sdk",
    transport: "claude-agent-sdk",
    vendorIds: ["anthropic"],
    visibility: "public",
    capabilities: [
      {
        id: "custom_tool_execute",
        status: "unsupported",
        version: 1,
      },
      {
        id: "input_start",
        status: "supported",
        version: 1,
      },
      {
        id: "mcp_execute",
        status: "supported",
        version: 1,
      },
      {
        id: "native_resume",
        status: "supported",
        version: 1,
      },
      {
        id: "permission_request",
        status: "supported",
        version: 1,
      },
      {
        id: "session_stop",
        status: "supported",
        version: 1,
      },
      {
        id: "thinking_stream",
        status: "supported",
        version: 1,
      },
      {
        id: "text_stream",
        status: "supported",
        version: 1,
      },
      {
        id: "tool_stream",
        status: "supported",
        version: 1,
      },
      {
        id: "turn_cancel",
        status: "supported",
        version: 1,
      },
      {
        id: "usage",
        status: "supported",
        version: 1,
      },
      {
        id: "visible_activity",
        status: "supported",
        version: 1,
      },
    ],
    supportedModelIds: [
      "claude-opus-4-7",
      "claude-opus-4-6",
      "claude-opus-4-5",
      "claude-sonnet-4-6",
      "claude-sonnet-4-5",
      "claude-haiku-4-5",
    ],
  },
  {
    acceptsCustomProvider: true,
    defaultIdentity: {
      modelId: "gpt-5.4",
      providerId: "openai",
    },
    disabledReason: "System Agent is an internal configuration helper.",
    display: {
      iconKey: "openai",
      providerLabel: "OpenAI",
    },
    label: "System Agent",
    runtimeId: "system-agent",
    transport: "openai-app-server",
    vendorIds: ["openai"],
    visibility: "internal",
    capabilities: [],
    supportedModelIds: ["gpt-5.5", "gpt-5.4", "gpt-5.4-mini", "gpt-5.3", "gpt-5.2"],
  },
  {
    acceptsCustomProvider: true,
    defaultIdentity: {
      modelId: "gpt-5.4",
      providerId: "openai",
    },
    display: {
      color: "#7A9DFF",
      iconKey: "openai",
      providerLabel: "OpenAI",
      showcaseLabel: "OpenAI",
    },
    label: "OpenAI Runtime",
    runtimeId: "openai-runtime",
    transport: "openai-app-server",
    vendorIds: ["openai"],
    visibility: "public",
    capabilities: [
      {
        id: "custom_tool_execute",
        status: "unsupported",
        version: 1,
      },
      {
        id: "input_start",
        status: "supported",
        version: 1,
      },
      {
        id: "mcp_execute",
        status: "supported",
        version: 1,
      },
      {
        id: "native_resume",
        status: "supported",
        version: 1,
      },
      {
        id: "permission_request",
        status: "supported",
        version: 1,
      },
      {
        id: "session_stop",
        status: "supported",
        version: 1,
      },
      {
        id: "thinking_stream",
        status: "supported",
        version: 1,
      },
      {
        id: "text_stream",
        status: "supported",
        version: 1,
      },
      {
        id: "tool_stream",
        status: "supported",
        version: 1,
      },
      {
        id: "turn_cancel",
        status: "supported",
        version: 1,
      },
      {
        id: "usage",
        status: "supported",
        version: 1,
      },
      {
        id: "visible_activity",
        status: "supported",
        version: 1,
      },
    ],
    supportedModelIds: ["gpt-5.5", "gpt-5.4", "gpt-5.4-mini", "gpt-5.3", "gpt-5.2"],
  },
  {
    acceptsCustomProvider: false,
    defaultIdentity: {
      modelId: "gpt-5.4",
      providerId: "openai",
    },
    display: {
      iconKey: "opencode",
      providerLabel: "OpenCode",
    },
    label: "OpenCode",
    runtimeId: "acp-fallback",
    transport: "acp-fallback",
    vendorIds: ["openai", "anthropic", "deepseek", "opencode"],
    visibility: "public",
    capabilities: [
      {
        id: "custom_tool_execute",
        status: "unsupported",
        version: 1,
      },
      {
        id: "input_start",
        status: "supported",
        version: 1,
      },
      {
        id: "mcp_execute",
        status: "supported",
        version: 1,
      },
      {
        id: "native_resume",
        status: "supported",
        version: 1,
      },
      {
        id: "permission_request",
        status: "supported",
        version: 1,
      },
      {
        id: "session_stop",
        status: "supported",
        version: 1,
      },
      {
        id: "thinking_stream",
        status: "supported",
        version: 1,
      },
      {
        id: "text_stream",
        status: "supported",
        version: 1,
      },
      {
        id: "tool_stream",
        status: "supported",
        version: 1,
      },
      {
        id: "turn_cancel",
        status: "supported",
        version: 1,
      },
      {
        id: "usage",
        status: "supported",
        version: 1,
      },
      {
        id: "visible_activity",
        status: "supported",
        version: 1,
      },
    ],
    supportedModelIds: [
      "claude-opus-4-7",
      "claude-opus-4-6",
      "claude-opus-4-5",
      "claude-sonnet-4-6",
      "claude-sonnet-4-5",
      "claude-haiku-4-5",
      "gpt-5.5",
      "gpt-5.4",
      "gpt-5.4-mini",
      "gpt-5.3",
      "gpt-5.2",
      "deepseek-v4-pro",
      "qwen3.6-plus",
      "glm-5.2",
      "minimax-m2.7",
      "gemini-3.5-flash",
    ],
  },
] as const;

export const GENERATED_PLANNED_RUNTIME_DISPLAY_CATALOG = [] as const;
