// Generated by pkgs/runtime-catalog/scripts/generate-runtime-catalog.ts.
// Source: pkgs/runtime-catalog/catalog/runtime-catalog.jsonc
// Do not edit this file by hand.

export const GENERATED_RUNTIME_ICON_KEYS: Record<string, string> = {
  "claude-agent-sdk": "claude-code",
  "system-agent": "openai",
  "openai-runtime": "openai",
  "acp-fallback": "opencode",
};
